// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOOWCAdQkNhA0ZLBYNHrwYUde36ioKq1Y',
    appId: '1:1035927122108:web:7c9491eae706161194e0b9',
    messagingSenderId: '1035927122108',
    projectId: 'talk-buddy-8ab7b',
    authDomain: 'talk-buddy-8ab7b.firebaseapp.com',
    storageBucket: 'talk-buddy-8ab7b.appspot.com',
    measurementId: 'G-Q86ZZ8ZZRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRAMejPtdZcSWDGdiuXVUws4BXyzPHsM',
    appId: '1:1035927122108:android:7e2d086c6a94621e94e0b9',
    messagingSenderId: '1035927122108',
    projectId: 'talk-buddy-8ab7b',
    storageBucket: 'talk-buddy-8ab7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCJVV8qWinaMI-8qnuLPhfruRBpRLRrU',
    appId: '1:1035927122108:ios:ce1ac10fa55d753494e0b9',
    messagingSenderId: '1035927122108',
    projectId: 'talk-buddy-8ab7b',
    storageBucket: 'talk-buddy-8ab7b.appspot.com',
    iosBundleId: 'com.example.talkbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCJVV8qWinaMI-8qnuLPhfruRBpRLRrU',
    appId: '1:1035927122108:ios:6a07e9e63c64f9ec94e0b9',
    messagingSenderId: '1035927122108',
    projectId: 'talk-buddy-8ab7b',
    storageBucket: 'talk-buddy-8ab7b.appspot.com',
    iosBundleId: 'com.example.talkbuddy.RunnerTests',
  );
}
